/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h33074d78573b8cea: (a: number, b: number) => void;
export const closure3063_externref_shim: (a: number, b: number, c: any) => void;
export const closure3057_externref_shim: (a: number, b: number, c: any) => void;
export const closure3059_externref_shim: (a: number, b: number, c: any) => void;
export const closure3061_externref_shim: (a: number, b: number, c: any) => void;
export const closure4864_externref_shim: (a: number, b: number, c: any) => void;
export const closure4866_externref_shim: (a: number, b: number, c: any) => void;
export const closure4870_externref_shim: (a: number, b: number, c: any) => void;
export const closure4868_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0f90e54e3d652b01: (a: number, b: number) => void;
export const closure4860_externref_shim: (a: number, b: number, c: any) => void;
export const closure4862_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hcb55d1e9118615d5: (a: number, b: number, c: number) => void;
export const closure4858_externref_shim: (a: number, b: number, c: any) => void;
export const closure4874_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h4f2dd92d5ea48018: (a: number, b: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb782c4508dc6ae58: (a: number, b: number) => void;
export const closure64539_externref_shim: (a: number, b: number, c: any) => void;
export const __wbindgen_start: () => void;
